plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ferme'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.2'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'ferme.ui.SmartFarmApp'
}

tasks.named('compileJava') {
    dependsOn tasks.named('processResources')
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add('-Xlint:-unchecked')
}

sourceSets {
    main {
        java {
            srcDirs = ['.']
            exclude 'bin/**', 'out/**', '**/.git/**', '**/.codex/**', '**/.agents/**', '**/*.class'
        }
        resources {
            srcDirs = ['.']
            include 'ferme/ui/**/*.fxml', 'ferme/ui/**/*.css'
        }
    }
}
